/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.frauas.Bustravelio.frontend;

import de.frauas.Bustravelio.backend.DBHandler;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.commons.lang3.StringUtils;
import org.apache.commons.validator.routines.EmailValidator;


public class CodegeneratorForAdmin extends javax.swing.JFrame {
    /**
     * Creates new form CodegeneratorForAdmin
     */
    public CodegeneratorForAdmin() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        euroTextField = new javax.swing.JTextField();
        mailTextField = new javax.swing.JTextField();
        generateCouponButton = new javax.swing.JButton();
        halloAdminLabel = new javax.swing.JLabel();
        mailLabel = new javax.swing.JLabel();
        labelfrom = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();
        euroLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Coupon Generator");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(254, 245, 245));
        kGradientPanel1.setkGradientFocus(0);
        kGradientPanel1.setkStartColor(new java.awt.Color(47, 62, 96));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        euroTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                euroTextFieldActionPerformed(evt);
            }
        });
        kGradientPanel1.add(euroTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 230, 40));

        mailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailTextFieldActionPerformed(evt);
            }
        });
        kGradientPanel1.add(mailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 230, 40));

        generateCouponButton.setBackground(new java.awt.Color(0, 0, 0));
        generateCouponButton.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        generateCouponButton.setForeground(new java.awt.Color(255, 255, 255));
        generateCouponButton.setText("Generate coupons");
        generateCouponButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        generateCouponButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateCouponButtonActionPerformed(evt);
            }
        });
        kGradientPanel1.add(generateCouponButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 190, 40));

        halloAdminLabel.setFont(new java.awt.Font("Avenir Next", 1, 36)); // NOI18N
        halloAdminLabel.setForeground(new java.awt.Color(255, 255, 255));
        halloAdminLabel.setText("Hello Admin");
        kGradientPanel1.add(halloAdminLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 230, -1));

        mailLabel.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        mailLabel.setText("Please enter the email address of the person :");
        kGradientPanel1.add(mailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        labelfrom.setFont(new java.awt.Font("Avenir Next", 0, 24)); // NOI18N
        labelfrom.setForeground(new java.awt.Color(255, 255, 255));
        labelfrom.setText("BusTravelio");
        kGradientPanel1.add(labelfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        infoLabel.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        infoLabel.setText("Each TravelioCoin is 1€");
        kGradientPanel1.add(infoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 170, -1));

        euroLabel.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        euroLabel.setText("Please enter the amount in € :");
        kGradientPanel1.add(euroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 250, 20));

        jPanel1.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void euroTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_euroTextFieldActionPerformed
        
        
    }//GEN-LAST:event_euroTextFieldActionPerformed

    private void mailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailTextFieldActionPerformed

    private void generateCouponButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateCouponButtonActionPerformed
        final int n = 10;
        String code = RGenerator.coupon(n);
        String mail = mailTextField.getText();
        double codep = 0;
        try
        {
            codep = Double.parseDouble(euroTextField.getText());
            // Valid double
        }
        catch (NullPointerException | NumberFormatException ex)
        {
        // Not valid double
        }
        // Euro String is Numeric and not text 
        // Check Email (Validate or not)
        boolean isNumeric = StringUtils.isNumeric(euroTextField.getText());
        boolean Validate= EmailValidator.getInstance().isValid(mail);
        if (!isNumeric){
            JOptionPane.showMessageDialog(null,"please enter a valide Euro-number","ERROR", JOptionPane.ERROR_MESSAGE);
        }else if(euroTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"please enter a valide Euro-number","ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else if( Validate== false || mail.isEmpty())
        {
              JOptionPane.showMessageDialog(null, "Please enter a valid E-Mail address!","ERROR", JOptionPane.ERROR_MESSAGE); 
        }
        else{
            DBHandler db = new DBHandler();
            int i = 1;
            db.paymentCoupons(code, codep, mail,i);
            JOptionPane.showMessageDialog(null,"Successfully created");
            System.out.println(codep);
            String subject = "Your Luxcoin Code";
            String info = "Hello\nnice that you use Luxpayment and grab the opportunity to buy tickets cheap and invest in Luxcoin at the same time.\n\n\n You can top up your account with the code:  " +code+"\n\nwe wish you a good day\n\n LuxBus";
            SendEMail send = new SendEMail();
            String newinfo = "\n\n\n\n";
            try {
                send.sendMail(mail, info,newinfo, subject, null);
            }catch (Exception ex) {
                Logger.getLogger(CodegeneratorForAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
            dispose();
        }
        
    }//GEN-LAST:event_generateCouponButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel euroLabel;
    private javax.swing.JTextField euroTextField;
    private javax.swing.JButton generateCouponButton;
    private javax.swing.JLabel halloAdminLabel;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel labelfrom;
    private javax.swing.JLabel mailLabel;
    private javax.swing.JTextField mailTextField;
    // End of variables declaration//GEN-END:variables

    
}
