/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.frauas.Bustravelio.frontend;

import de.frauas.Bustravelio.backend.DBHandler;
import de.frauas.Bustravelio.backend.Encryption;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.apache.commons.validator.routines.EmailValidator;

/**
 *
 * @author haith
 */
public class CreateAccountPayment extends javax.swing.JFrame {

    /**
     * Creates new form CreateAccountPayment
     */
    public CreateAccountPayment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LuxcoinLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        usernamePaymentTextField = new javax.swing.JTextField();
        firstNamePaymentTextField = new javax.swing.JTextField();
        lastNamePaymentTextField = new javax.swing.JTextField();
        addressPaymentTextField = new javax.swing.JTextField();
        eMailPaymentTextField = new javax.swing.JTextField();
        createPasswordPaymentTextField = new javax.swing.JPasswordField();
        rewritePasswordPaymentTextField = new javax.swing.JPasswordField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        lastNamePaymentLabel = new javax.swing.JLabel();
        firstNamePaymentLable = new javax.swing.JLabel();
        UserNamePaymentLabel = new javax.swing.JLabel();
        AddressPaymentLabel = new javax.swing.JLabel();
        eMailPaymentLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rewritePasswordPaymentLabel = new javax.swing.JLabel();
        createPasswordPaymetLabel = new javax.swing.JLabel();
        CreateAccountPaymentButton = new javax.swing.JButton();
        labelfrom = new javax.swing.JLabel();
        luxpaymentCreateAccountLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sign up LUXPAYMENT");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LuxcoinLabel1.setFont(new java.awt.Font("Ayuthaya", 1, 36)); // NOI18N
        LuxcoinLabel1.setForeground(new java.awt.Color(255, 255, 255));
        LuxcoinLabel1.setText("TravelioCoin");
        getContentPane().add(LuxcoinLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 54));

        jLabel3.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Payment now one step easier ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 390, -1));

        kGradientPanel1.setkEndColor(new java.awt.Color(254, 245, 245));
        kGradientPanel1.setkGradientFocus(50);
        kGradientPanel1.setkStartColor(new java.awt.Color(47, 62, 96));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernamePaymentTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernamePaymentTextFieldActionPerformed(evt);
            }
        });
        kGradientPanel1.add(usernamePaymentTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 230, 30));

        firstNamePaymentTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNamePaymentTextFieldActionPerformed(evt);
            }
        });
        kGradientPanel1.add(firstNamePaymentTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 230, 30));
        kGradientPanel1.add(lastNamePaymentTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 230, 30));
        kGradientPanel1.add(addressPaymentTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 230, 30));
        kGradientPanel1.add(eMailPaymentTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 230, 30));
        kGradientPanel1.add(createPasswordPaymentTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 230, 30));
        kGradientPanel1.add(rewritePasswordPaymentTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 230, 30));

        jDateChooser1.setDateFormatString("dd.MM.yyyy");
        jDateChooser1.setOpaque(false);
        kGradientPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, 230, 30));

        lastNamePaymentLabel.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        lastNamePaymentLabel.setText("Last Name:");
        kGradientPanel1.add(lastNamePaymentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 120, -1));

        firstNamePaymentLable.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        firstNamePaymentLable.setText("First Name:");
        kGradientPanel1.add(firstNamePaymentLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 120, 30));

        UserNamePaymentLabel.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        UserNamePaymentLabel.setText("Username:");
        kGradientPanel1.add(UserNamePaymentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 160, 100, 30));

        AddressPaymentLabel.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        AddressPaymentLabel.setText("Address:");
        kGradientPanel1.add(AddressPaymentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 130, -1));

        eMailPaymentLabel.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        eMailPaymentLabel.setText("E-Mail Address:");
        kGradientPanel1.add(eMailPaymentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 140, -1));

        jLabel1.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        jLabel1.setText("Date of birth :");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 140, -1));

        rewritePasswordPaymentLabel.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        rewritePasswordPaymentLabel.setText("Rewrite password:");
        kGradientPanel1.add(rewritePasswordPaymentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 410, 190, -1));

        createPasswordPaymetLabel.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        createPasswordPaymetLabel.setText("Create password:");
        kGradientPanel1.add(createPasswordPaymetLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 160, -1));

        CreateAccountPaymentButton.setBackground(new java.awt.Color(0, 0, 0));
        CreateAccountPaymentButton.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        CreateAccountPaymentButton.setForeground(new java.awt.Color(255, 255, 255));
        CreateAccountPaymentButton.setText("Create");
        CreateAccountPaymentButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        CreateAccountPaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAccountPaymentButtonActionPerformed(evt);
            }
        });
        kGradientPanel1.add(CreateAccountPaymentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 140, 40));

        labelfrom.setFont(new java.awt.Font("Avenir Next", 0, 24)); // NOI18N
        labelfrom.setText("BusTravelio ");
        kGradientPanel1.add(labelfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 600, 230, 30));

        luxpaymentCreateAccountLabel.setFont(new java.awt.Font("Avenir Next", 1, 36)); // NOI18N
        luxpaymentCreateAccountLabel.setForeground(new java.awt.Color(255, 255, 255));
        luxpaymentCreateAccountLabel.setText(" Create Account");
        kGradientPanel1.add(luxpaymentCreateAccountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 280, -1));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstNamePaymentTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNamePaymentTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNamePaymentTextFieldActionPerformed

    private void CreateAccountPaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAccountPaymentButtonActionPerformed
        
        boolean Validate= EmailValidator.getInstance().isValid(eMailPaymentTextField.getText());
        
        if( Validate== false)
        {
              JOptionPane.showMessageDialog(null, "Please enter a valid E-Mail address!","ERROR", JOptionPane.ERROR_MESSAGE); 
        }
        else
        {
       DBHandler mydbhandler= new DBHandler();
       String password = createPasswordPaymentTextField.getText();
       String confirmationPassword= rewritePasswordPaymentTextField.getText();
       boolean createUser= true;
       
       ResultSet rsForUser= mydbhandler.Selectdata("paymentUsers", "usernamep",  usernamePaymentTextField.getText());
       ResultSet rsForEmail= mydbhandler.Selectdata("paymentUsers", "emailp",  eMailPaymentTextField.getText());

       if (mydbhandler.checkstatmentExsist(rsForUser))
       {
            JOptionPane.showMessageDialog(null, "please take other username","ERROR", JOptionPane.ERROR_MESSAGE);
            createUser=false;
       }
        if (mydbhandler.checkstatmentExsist(rsForEmail))
       {
            JOptionPane.showMessageDialog(null, "E-Mail is already exists","ERROR", JOptionPane.ERROR_MESSAGE);
            createUser=false;
       }
       //System.out.println(password+ " "+confirmationPassword);
       if(!password.equals(confirmationPassword))
        {
           JOptionPane.showMessageDialog(null, "Password and Password Confirmation are not equal!","ERROR", JOptionPane.ERROR_MESSAGE);
            createUser=false;
        }
       
       //get information to insert them in DB newUser
       
        String firstname= firstNamePaymentTextField.getText();
        String lastname= lastNamePaymentTextField.getText();
        String username= usernamePaymentTextField.getText();
        String email= eMailPaymentTextField.getText();
        String address = addressPaymentTextField.getText();
        String dob = ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();

                //jDateChooser1.get;
        
        if( createUser){
                Encryption enc= new Encryption(password);
                String hash= enc.HaschCode();
                mydbhandler.newUserPayment(firstname, lastname, username, hash, address, email, dob);
                mydbhandler.createUserstoryP(username);
                JOptionPane.showMessageDialog(null, "Successfully completed","INFO", JOptionPane.INFORMATION_MESSAGE);
                dispose();
        }
        }
    }//GEN-LAST:event_CreateAccountPaymentButtonActionPerformed

    private void usernamePaymentTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamePaymentTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernamePaymentTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressPaymentLabel;
    public static javax.swing.JButton CreateAccountPaymentButton;
    private javax.swing.JLabel LuxcoinLabel1;
    private javax.swing.JLabel UserNamePaymentLabel;
    public static javax.swing.JTextField addressPaymentTextField;
    public static javax.swing.JPasswordField createPasswordPaymentTextField;
    private javax.swing.JLabel createPasswordPaymetLabel;
    private javax.swing.JLabel eMailPaymentLabel;
    public static javax.swing.JTextField eMailPaymentTextField;
    private javax.swing.JLabel firstNamePaymentLable;
    public javax.swing.JTextField firstNamePaymentTextField;
    public static com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel labelfrom;
    private javax.swing.JLabel lastNamePaymentLabel;
    public static javax.swing.JTextField lastNamePaymentTextField;
    private javax.swing.JLabel luxpaymentCreateAccountLabel;
    private javax.swing.JLabel rewritePasswordPaymentLabel;
    public static javax.swing.JPasswordField rewritePasswordPaymentTextField;
    public static javax.swing.JTextField usernamePaymentTextField;
    // End of variables declaration//GEN-END:variables

}
