/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.frauas.Bustravelio.frontend;

import de.frauas.Bustravelio.backend.DBHandler;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author haith
 */
public class GiveCouponUser extends javax.swing.JFrame {
    String username;
    /**
     * Creates new form GiveCouponUser
     * @param username
     */
    public GiveCouponUser(String username) {
        this.username=username;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        tenDigitTextFieled = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();
        labelfrom = new javax.swing.JLabel();
        tenDigitLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reedem Coupon");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(254, 245, 245));
        kGradientPanel1.setkGradientFocus(0);
        kGradientPanel1.setkStartColor(new java.awt.Color(47, 62, 96));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tenDigitTextFieled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenDigitTextFieledActionPerformed(evt);
            }
        });
        kGradientPanel1.add(tenDigitTextFieled, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 230, 40));

        SubmitButton.setBackground(new java.awt.Color(0, 0, 0));
        SubmitButton.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        SubmitButton.setForeground(new java.awt.Color(255, 255, 255));
        SubmitButton.setText("Submit");
        SubmitButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });
        kGradientPanel1.add(SubmitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 140, 40));

        labelfrom.setFont(new java.awt.Font("Avenir Next", 0, 24)); // NOI18N
        labelfrom.setForeground(new java.awt.Color(255, 255, 255));
        labelfrom.setText("BusTravelio");
        kGradientPanel1.add(labelfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        tenDigitLabel.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        tenDigitLabel.setText("Give your ten-digit code here:");
        kGradientPanel1.add(tenDigitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 260, 23));

        jLabel1.setFont(new java.awt.Font("Avenir Next", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reedem Coupon");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 200, 40));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tenDigitTextFieledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenDigitTextFieledActionPerformed
        
    }//GEN-LAST:event_tenDigitTextFieledActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        int i = 0;
        DBHandler mydbhandler= new DBHandler();
        ResultSet checkSec = mydbhandler.checkcoupons(tenDigitTextFieled.getText());
        if(tenDigitTextFieled.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"please enter a valid Code");
        }
        else if (!mydbhandler.checkstatmentExsist(checkSec))
        {
           JOptionPane.showMessageDialog(null,"the code dose not exists or it was used");
        }
        else {
            try {
                price = mydbhandler.SelectPrice("Price", "codep", tenDigitTextFieled.getText()); 
            } catch (SQLException ex) {
                Logger.getLogger(GiveCouponUser.class.getName()).log(Level.SEVERE, null, ex);
            }
            double amount = Double.parseDouble(price);
            String currentamount = null;
            String lastprice = null;
            try {
                currentamount = mydbhandler.SelectPriceFromUsers("currentp", "usernamep", username);
            } catch (SQLException ex) {
                Logger.getLogger(GiveCouponUser.class.getName()).log(Level.SEVERE, null, ex);
            }
            double currentAmount2 = Double.parseDouble(currentamount);
            currentAmount2 += amount;
            lastprice = Double.toString(currentAmount2);
            mydbhandler.UpdatePayment2("currentp", lastprice, username);
            mydbhandler.Updatecoupon(tenDigitTextFieled.getText());
            DateAndTime dANDt = new DateAndTime();
            String date = dANDt.getDate();
            String time = dANDt.getTime();
            String sentOrReceived = "Received";
            String sentTo = "----";
            String received = "Coupoun code";
            
            
            System.out.println("Username "+username+"\ndate ======> "+date+"\ntime ======>"+ time);
            mydbhandler.insertUserstoryP(username, sentOrReceived, sentTo, received, amount, date, time);
            JOptionPane.showMessageDialog(null,"please login with your payment to see the current status");
        }
            dispose();
    }//GEN-LAST:event_SubmitButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton SubmitButton;
    private javax.swing.JLabel jLabel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel labelfrom;
    private javax.swing.JLabel tenDigitLabel;
    public javax.swing.JTextField tenDigitTextFieled;
    // End of variables declaration//GEN-END:variables

    String price;
}
