/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.frauas.Bustravelio.frontend;

import de.frauas.Bustravelio.backend.DBHandler;
import de.frauas.Bustravelio.backend.Encryption;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author haith
 */
public class LastBook extends javax.swing.JFrame {
    int id;
String fromcity;
String tocity;
String Datum;
String departureTime;
String arriveTime;
double price;
int seat;
int seatdb;
String username="Gast";
ButtonGroup gengp=new ButtonGroup(); 
    /**
     * Creates new form LastBook
     */

    public LastBook(int id ,String fromcity, String tocity, String Datum, String departureTime, String arriveTime, double price,int seat, int seatdb) {
        this.id=id;
        this.fromcity=fromcity;
        this.tocity=tocity;
        this.Datum=Datum;
        this.departureTime=departureTime;
        this.arriveTime=arriveTime;
        this.price = price;
        this.seat=seat;
        this.seatdb=seatdb;
        initComponents();
    }

   
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        usernemeTextField = new javax.swing.JTextField();
        passwordField1 = new javax.swing.JPasswordField();
        spotCheckBox = new javax.swing.JCheckBox();
        usernemeTextField1 = new javax.swing.JTextField();
        luxcoinCheckBox = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelfrom = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        LuxcoinLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select Payment");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(254, 245, 245));
        kGradientPanel1.setkGradientFocus(0);
        kGradientPanel1.setkStartColor(new java.awt.Color(47, 62, 96));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernemeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernemeTextFieldActionPerformed(evt);
            }
        });
        kGradientPanel1.add(usernemeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 290, 50));

        passwordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordField1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(passwordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 290, 50));

        gengp.add(spotCheckBox);
        spotCheckBox.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        spotCheckBox.setText("pay before departure");
        spotCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spotCheckBoxActionPerformed(evt);
            }
        });
        kGradientPanel1.add(spotCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 220, 220, -1));

        usernemeTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernemeTextField1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(usernemeTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 400, 290, 50));

        gengp.add(luxcoinCheckBox);
        luxcoinCheckBox.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        luxcoinCheckBox.setText("pay with Luxcoin");
        kGradientPanel1.add(luxcoinCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 261, -1));

        jLabel6.setFont(new java.awt.Font("Avenir Next", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(47, 62, 96));
        jLabel6.setText("Tipp: Create a TravelioCoin Account");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 590, 260, -1));

        nextButton.setBackground(new java.awt.Color(0, 0, 0));
        nextButton.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        nextButton.setForeground(new java.awt.Color(255, 255, 255));
        nextButton.setText("Next ");
        nextButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        kGradientPanel1.add(nextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 30, 140, 40));

        jLabel4.setFont(new java.awt.Font("Avenir Next", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(47, 62, 96));
        jLabel4.setText(""+price+" €");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 540, -1, 53));

        jLabel8.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(254, 245, 245));
        jLabel8.setText("*Please select a method of payment before continuing ");
        kGradientPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Avenir Next", 0, 24)); // NOI18N
        jLabel9.setText("TravelioCoin");
        kGradientPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 154, -1));

        jLabel10.setFont(new java.awt.Font("Avenir Next", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Select Payment");
        kGradientPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, 280, -1));

        labelfrom.setFont(new java.awt.Font("Avenir Next", 0, 24)); // NOI18N
        labelfrom.setForeground(new java.awt.Color(255, 255, 255));
        labelfrom.setText("BusTravelio");
        kGradientPanel1.add(labelfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 30));

        jLabel11.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("E-Mail address");
        kGradientPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 370, 190, -1));

        jLabel12.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Username ");
        kGradientPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 154, -1));

        jLabel13.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Password");
        kGradientPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 154, -1));

        jLabel14.setFont(new java.awt.Font("Avenir Next", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Amount payable:");
        kGradientPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 540, 250, 53));

        LuxcoinLabel1.setFont(new java.awt.Font("Ayuthaya", 1, 36)); // NOI18N
        LuxcoinLabel1.setText("TravelioCoin");
        kGradientPanel1.add(LuxcoinLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 800, 270, 54));

        jLabel15.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLabel15.setText("Payment now one step easier ");
        kGradientPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 850, 390, -1));

        jPanel1.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 900));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spotCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spotCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spotCheckBoxActionPerformed

    private void passwordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordField1ActionPerformed
    
    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        if (luxcoinCheckBox.isSelected()){
            String username = usernemeTextField.getText();
             String pw = passwordField1.getText();
            Encryption enc = new Encryption(pw);
            String hash= enc.HaschCode();
            DBHandler mydbhandler= new DBHandler();
            ResultSet checkSec= mydbhandler.SelectData2colmn("paymentUsers", "usernamep", "passwordp",username,hash);
            String currentamount = null;
            
            if(usernemeTextField.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"please enter a valid Username");
            }
            else if(passwordField1.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"please enter a valid password");
            }
            else if (!mydbhandler.checkstatmentExsist(checkSec))
            {
                JOptionPane.showMessageDialog(null,"Username or password are not correct");
            }
            else {
                try {
                    currentamount = mydbhandler.SelectPriceFromUsers("currentp", "usernamep", username);
                } catch (SQLException ex) {
                    Logger.getLogger(PaymentLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println("Aktuell amount =======>" + currentamount);
                double currentamoun2 = Double.parseDouble(currentamount);
                currentamoun2 -= price;
                if (currentamoun2 < 0){
                JOptionPane.showMessageDialog(null,"not available your balances are not sufficient");
                }
                else{
                String newCurrentamount = Double.toString(currentamoun2);
                mydbhandler.UpdatePayment2("currentp", newCurrentamount, username);
                System.out.println("Done alright");
                DateAndTime dANDt = new DateAndTime();
                String date = dANDt.getDate();
                String time = dANDt.getTime();
                String sentOrReceived = "Received for Tiket";
                String sentTo = "----";
                String received = "Luxpayment";
            
                System.out.println("Username "+username+"\ndate ======> "+date+"\ntime ======>"+ time);
                mydbhandler.insertUserstoryP(username, sentOrReceived, sentTo, received, price, date, time);
     //           mydbhandler.insertUserstoryT(username, fromcity, tocity, Datum, departureTime, arriveTime, price,seat);
            
            JOptionPane.showMessageDialog(null,"please login with your payment to see the current status");
            
            String nachricht = "thank you for your booking , here below you can see the booking information.\n\n";
                String info7 = "\n\nplease bring a negative covid-19 and be there about 10 minutes early\n\n";
                ExportPDF export = new ExportPDF();
                export.pdfExport(username, date, nachricht, "From : "+fromcity, "To : " + tocity, "Date : " + date, "Departure time : " +departureTime, "Arrive time : " + arriveTime, "Price : " + price, info7);
                String path = "d:/" + username + date + ".pdf";
                String subject = "Your Ticket";
                String info = "Hello\nnice that you use Luxpayment and grab the opportunity to buy tickets cheap and invest in Luxcoin at the same time.\n\n\n You see your Ticket information attached with this mail as pdf\n\n\n";
                SendEMail send = new SendEMail();
                String newinfo = "\n\n\n\n";
                String email = null;
                try {
                    email = mydbhandler.SelectemailFromUsers("emailp", "usernamep", username);
                } catch (SQLException ex) {
                    Logger.getLogger(LastBook.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    send.sendMail(email, info,newinfo, subject, path);
                } catch (Exception ex) {
                    Logger.getLogger(LastBook.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println("Email ===> "+email);
            
                int seattodb=seatdb-seat;
                mydbhandler.inserttravels(  id, seattodb);
                dispose();
                }
            }
        }
        else if(spotCheckBox.isSelected()) {
            
            JOptionPane.showMessageDialog(null,"please be there a little earlier from the departure to be able to pay at service point ");
            JOptionPane.showMessageDialog(null,"successfully reserved, if you are not there before one hour before departure your trip will be disabled ");
            
            DBHandler mydbhandler= new DBHandler();

            
             String nachricht = "Thank you for your booking , here below you can see the booking information.\n\n";
                String info7 = "\n\nplease bring a negative covid-19 and be there about 10 minutes early\n\n";
                ExportPDF export = new ExportPDF();
                export.pdfExport(username, Datum, nachricht, "From : "+fromcity, "To : " + tocity, "Date : " + Datum, "Departure time : " +departureTime, "Arrive time : " + arriveTime, "Price : " + price, info7);
                String path = "d:/" + username + Datum + ".pdf";
                String subject = "Your Ticket";
                String info = "Welcome ,\n" +
                "Thank you for using our service, we wish you a pleasant trip.\n" +
                "Please do not forget to come before so that you can complete your payment.\n\n\n You see your Ticket information attached with this mail as pdf\n\n\n";
                SendEMail send = new SendEMail();
                String newinfo = "\n\n\n\n";
                String email = usernemeTextField1.getText();
                email = usernemeTextField1.getText();
                try {
                    send.sendMail(email, info,newinfo, subject, path);
                } catch (Exception ex) {
                    Logger.getLogger(LastBook.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println("Email ===> "+email);
            
              int seattodb=seatdb-seat;
                mydbhandler.inserttravels(  id, seattodb);
            dispose();
           
        }
        else {
            JOptionPane.showMessageDialog(null,"please select the Payment method");
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void usernemeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernemeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernemeTextFieldActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        new CreateAccountPayment().setVisible(true);;
    }//GEN-LAST:event_jLabel6MouseClicked

    private void usernemeTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernemeTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernemeTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LuxcoinLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel labelfrom;
    private javax.swing.JCheckBox luxcoinCheckBox;
    private javax.swing.JButton nextButton;
    private javax.swing.JPasswordField passwordField1;
    private javax.swing.JCheckBox spotCheckBox;
    public javax.swing.JTextField usernemeTextField;
    public javax.swing.JTextField usernemeTextField1;
    // End of variables declaration//GEN-END:variables

  

}
