/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package de.frauas.Bustravelio.frontend;
import de.frauas.Bustravelio.backend.DBHandler;
import de.frauas.Bustravelio.backend.Encryption;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Login2 extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    String username;
    int id;
    String fromcity;
    String tocity;
    String Datum;
    String departureTime;
    String arriveTime;
    double price;
    int seat;
    int seatdb;
    public Login2(String username,int id ,String fromcity, String tocity, String Datum, String departureTime, String arriveTime, double price,int seat, int seatdb) {
        initComponents();
        
        this.username=username;
        this.id=id;
        this.fromcity=fromcity;
        this.tocity=tocity;
        this.Datum=Datum;
        this.departureTime=departureTime;
        this.arriveTime=arriveTime;
        this.price=price;
        this.seat=seat;
        this.seatdb=seatdb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelfrom = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        UsernamejLabel1 = new javax.swing.JLabel();
        PasswordjLabel1 = new javax.swing.JLabel();
        LuxcoinLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        UsernamejTextField1 = new javax.swing.JTextField();
        PasswordjTextField1 = new javax.swing.JPasswordField();
        showPassword = new javax.swing.JCheckBox();
        RegisterjButton1 = new javax.swing.JButton();
        loginjButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BusTravelio Login");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelfrom.setFont(new java.awt.Font("Avenir Next", 0, 48)); // NOI18N
        labelfrom.setForeground(new java.awt.Color(255, 255, 255));
        labelfrom.setText("BusTravelio");
        getContentPane().add(labelfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 70));

        jLabel1.setFont(new java.awt.Font("Avenir", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 170, 70));

        UsernamejLabel1.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        UsernamejLabel1.setText("Username:");
        getContentPane().add(UsernamejLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 101, -1));

        PasswordjLabel1.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        PasswordjLabel1.setText("Password:");
        getContentPane().add(PasswordjLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 90, -1));

        LuxcoinLabel2.setFont(new java.awt.Font("Ayuthaya", 1, 36)); // NOI18N
        LuxcoinLabel2.setText("TravelioCoin");
        getContentPane().add(LuxcoinLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 810, 270, 54));

        jLabel13.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLabel13.setText("Payment now one step easier ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 860, 190, -1));

        kGradientPanel1.setkEndColor(new java.awt.Color(254, 245, 245));
        kGradientPanel1.setkGradientFocus(0);
        kGradientPanel1.setkStartColor(new java.awt.Color(47, 62, 96));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsernamejTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernamejTextField1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(UsernamejTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 310, 50));

        PasswordjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordjTextField1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(PasswordjTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 310, 50));

        showPassword.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        showPassword.setText("show password");
        showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordActionPerformed(evt);
            }
        });
        kGradientPanel1.add(showPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, -1, -1));

        RegisterjButton1.setBackground(new java.awt.Color(0, 0, 0));
        RegisterjButton1.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        RegisterjButton1.setForeground(new java.awt.Color(255, 255, 255));
        RegisterjButton1.setText("Sign Up");
        RegisterjButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        RegisterjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterjButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(RegisterjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 550, 140, 40));

        loginjButton1.setBackground(new java.awt.Color(0, 0, 0));
        loginjButton1.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        loginjButton1.setForeground(new java.awt.Color(255, 255, 255));
        loginjButton1.setText("Sign In");
        loginjButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        loginjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginjButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(loginjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 550, 140, 40));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernamejTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernamejTextField1ActionPerformed
        
    }//GEN-LAST:event_UsernamejTextField1ActionPerformed

    private void loginjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginjButton1ActionPerformed
        String pw = PasswordjTextField1.getText();
        Encryption enc = new Encryption(pw);
        String hash= enc.HaschCode();
        
        DBHandler mydbhandler= new DBHandler();
        ResultSet checkSec= mydbhandler.SelectData2colmn("users", "username", "password",UsernamejTextField1.getText(),hash);
        if(UsernamejTextField1.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"please enter a valid Username");
        }
        else if(PasswordjTextField1.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"please enter a valid password");
        }
        if (!mydbhandler.checkstatmentExsist(checkSec)){
           JOptionPane.showMessageDialog(null,"username or passwor are not correct");
        }
        else {
            dispose();
            user user = mydbhandler.GetUser(UsernamejTextField1.getText());
            
            new LastBook(id , fromcity,  tocity,  Datum,  departureTime,  arriveTime,  price, seat,  seatdb).setVisible(true);

            /*if (!user.isAdmin)
            {   
                 username=UsernamejTextField1.getText();
               dispose();
               new StartWindowAfterLogin(username).setVisible(true);
            }
            else {
                  username=UsernamejTextField1.getText();
               dispose();
               new StartWindowAfterLoginAdmin(username).setVisible(true);
            }*/
        }
    }//GEN-LAST:event_loginjButton1ActionPerformed

    private void RegisterjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterjButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Register2(username,id , fromcity,  tocity,  Datum,  departureTime,  arriveTime,  price, seat,  seatdb).setVisible(true);
    }//GEN-LAST:event_RegisterjButton1ActionPerformed

    private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordActionPerformed
       showPassword.isSelected();
       if (evt.getSource() == showPassword) {
            if (showPassword.isSelected()) {
                PasswordjTextField1.setEchoChar((char) 0);
            }
            else {
                PasswordjTextField1.setEchoChar('*');
            } 
         }
       
    }//GEN-LAST:event_showPasswordActionPerformed

    private void PasswordjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordjTextField1ActionPerformed
        
    }//GEN-LAST:event_PasswordjTextField1ActionPerformed




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LuxcoinLabel2;
    private javax.swing.JLabel PasswordjLabel1;
    private javax.swing.JPasswordField PasswordjTextField1;
    private javax.swing.JButton RegisterjButton1;
    private javax.swing.JLabel UsernamejLabel1;
    public javax.swing.JTextField UsernamejTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel labelfrom;
    private javax.swing.JButton loginjButton1;
    private javax.swing.JCheckBox showPassword;
    // End of variables declaration//GEN-END:variables

//    private String username = null;
}
