/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.frauas.Bustravelio.frontend;

import de.frauas.Bustravelio.backend.DBHandler;
import de.frauas.Bustravelio.backend.Encryption;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import org.apache.commons.validator.routines.EmailValidator;





/**
 *
 * @author User
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        FirstnamejLabel1 = new javax.swing.JLabel();
        LastnamejLabel1 = new javax.swing.JLabel();
        UsernamejLabel1 = new javax.swing.JLabel();
        EmailjLabel2 = new javax.swing.JLabel();
        Password1jLabel1 = new javax.swing.JLabel();
        PasswordjLabel2 = new javax.swing.JLabel();
        labelfrom = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LuxcoinLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UsernamejTextField1 = new javax.swing.JTextField();
        FirstnamejTextField1 = new javax.swing.JTextField();
        LastnamejTextField1 = new javax.swing.JTextField();
        EmailAddressejTextField1 = new javax.swing.JTextField();
        PasswordjPasswordField2 = new javax.swing.JPasswordField();
        ConfirmjPasswordField1 = new javax.swing.JPasswordField();
        RegisterjButton1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BusTravelio Sign Up");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(254, 245, 245));
        kGradientPanel1.setkGradientFocus(75);
        kGradientPanel1.setkStartColor(new java.awt.Color(47, 62, 96));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox1.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        jCheckBox1.setText("Accept Terms And Conditions.");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 228, -1));

        FirstnamejLabel1.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        FirstnamejLabel1.setText("First name: ");
        kGradientPanel1.add(FirstnamejLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 115, 20));

        LastnamejLabel1.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        LastnamejLabel1.setText("Last name: ");
        kGradientPanel1.add(LastnamejLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 115, 20));

        UsernamejLabel1.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        UsernamejLabel1.setText("Username: ");
        kGradientPanel1.add(UsernamejLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 100, 20));

        EmailjLabel2.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        EmailjLabel2.setText("Email Addresse: ");
        kGradientPanel1.add(EmailjLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 140, 20));

        Password1jLabel1.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        Password1jLabel1.setText("Password: ");
        kGradientPanel1.add(Password1jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 115, 20));

        PasswordjLabel2.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        PasswordjLabel2.setText("Confirm Password: ");
        kGradientPanel1.add(PasswordjLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, 20));

        labelfrom.setFont(new java.awt.Font("Avenir Next", 0, 36)); // NOI18N
        labelfrom.setForeground(new java.awt.Color(255, 255, 255));
        labelfrom.setText("BusTravelio ");
        kGradientPanel1.add(labelfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 50));

        jLabel1.setFont(new java.awt.Font("Avenir Next", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("New Member");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        LuxcoinLabel1.setFont(new java.awt.Font("Ayuthaya", 1, 36)); // NOI18N
        LuxcoinLabel1.setText("TravelioCoin");
        kGradientPanel1.add(LuxcoinLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 570, 270, 54));

        jLabel3.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLabel3.setText("Payment now one step easier ");
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 620, 190, 20));
        kGradientPanel1.add(UsernamejTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 200, 30));
        kGradientPanel1.add(FirstnamejTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 200, 30));
        kGradientPanel1.add(LastnamejTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 200, 30));
        kGradientPanel1.add(EmailAddressejTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 200, 30));

        PasswordjPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordjPasswordField2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(PasswordjPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 200, 30));

        ConfirmjPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmjPasswordField1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(ConfirmjPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 200, 30));

        RegisterjButton1.setBackground(new java.awt.Color(0, 0, 0));
        RegisterjButton1.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        RegisterjButton1.setForeground(new java.awt.Color(255, 255, 255));
        RegisterjButton1.setText("Register");
        RegisterjButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        RegisterjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterjButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(RegisterjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 140, 40));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 140, 40));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterjButton1ActionPerformed
        // TODO add your handling code here:
        
        EmailAddressejTextField1.getText();
        
        boolean Validate= EmailValidator.getInstance().isValid(EmailAddressejTextField1.getText());
        
        if( Validate== false)
        {
              JOptionPane.showMessageDialog(null, "Please enter a valid E-Mail address!","ERROR", JOptionPane.ERROR_MESSAGE); 
        }
        else
        {
             if(jCheckBox1.isSelected()){
       DBHandler mydbhandler= new DBHandler();
       String password = new String(PasswordjPasswordField2.getPassword());
       String confirmationPassword= new String(ConfirmjPasswordField1.getPassword());
       Encryption enc= new Encryption(password);
       String hash= enc.HaschCode();
       boolean createUser= true;
       
       ResultSet rsForUser= mydbhandler.Selectdata("users", "username",  UsernamejTextField1.getText());
       ResultSet rsForEmail= mydbhandler.Selectdata("users", "emailaddress",  EmailAddressejTextField1.getText());

       if (mydbhandler.checkstatmentExsist(rsForUser))
       {
            
            JOptionPane.showMessageDialog(null, "Username is already exists","ERROR", JOptionPane.ERROR_MESSAGE);
            createUser=false;
            
        
       }
       if (mydbhandler.checkstatmentExsist(rsForEmail))
       {
            JOptionPane.showMessageDialog(null, "E-Mail is already exists","ERROR", JOptionPane.ERROR_MESSAGE);
            createUser=false;
       }
       //System.out.println(password+ " "+confirmationPassword);
       if(!password.equals(confirmationPassword))
        {
           JOptionPane.showMessageDialog(null, "Password and Password Confirmation are not equal!","ERROR", JOptionPane.ERROR_MESSAGE);
            createUser=false;
        }
       
       //get information to insert them in DB newUser
       
       String firstname= FirstnamejTextField1.getText();
        String lastname= LastnamejTextField1.getText();
        String username= UsernamejTextField1.getText();
        String email= EmailAddressejTextField1.getText();
        
        if( createUser)
        {
                mydbhandler.newUser("users",firstname, lastname, username,hash,email);

                JOptionPane.showMessageDialog(null, "Registration complete","INFO", JOptionPane.INFORMATION_MESSAGE);
                dispose();
        }
         }
     else{
    JOptionPane.showMessageDialog(null,"Please confirm our request");

     }
        }
             
    }//GEN-LAST:event_RegisterjButton1ActionPerformed

    private void PasswordjPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordjPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordjPasswordField2ActionPerformed

    private void ConfirmjPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmjPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmjPasswordField1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ConfirmjPasswordField1;
    private javax.swing.JTextField EmailAddressejTextField1;
    private javax.swing.JLabel EmailjLabel2;
    private javax.swing.JLabel FirstnamejLabel1;
    private javax.swing.JTextField FirstnamejTextField1;
    private javax.swing.JLabel LastnamejLabel1;
    private javax.swing.JTextField LastnamejTextField1;
    private javax.swing.JLabel LuxcoinLabel1;
    private javax.swing.JLabel Password1jLabel1;
    private javax.swing.JLabel PasswordjLabel2;
    private javax.swing.JPasswordField PasswordjPasswordField2;
    private javax.swing.JButton RegisterjButton1;
    private javax.swing.JLabel UsernamejLabel1;
    private javax.swing.JTextField UsernamejTextField1;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel labelfrom;
    // End of variables declaration//GEN-END:variables
}
