/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.frauas.Bustravelio.frontend;

import de.frauas.Bustravelio.backend.DBHandler;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author haith
 */
public class SendLuxcoin extends javax.swing.JFrame {
 String sender;
    /**
     * Creates new form SendLuxcoin
     * @param sender
     */
    public SendLuxcoin(String sender) {
        this.sender = sender;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        LuxcoinLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelfrom = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        purposeTextField = new javax.swing.JTextField();
        amountTextField = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Send TravelioCoins");

        jPanel1.setForeground(new java.awt.Color(165, 200, 200));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(254, 245, 245));
        kGradientPanel1.setkGradientFocus(0);
        kGradientPanel1.setkStartColor(new java.awt.Color(47, 62, 96));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LuxcoinLabel1.setFont(new java.awt.Font("Ayuthaya", 1, 36)); // NOI18N
        LuxcoinLabel1.setForeground(new java.awt.Color(255, 255, 255));
        LuxcoinLabel1.setText("TravelioCoin");
        kGradientPanel1.add(LuxcoinLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 54));

        jLabel6.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Payment now one step easier ");
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 390, -1));

        jLabel5.setFont(new java.awt.Font("Avenir Next", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Send TravelioCoins");
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        jLabel7.setText("Username of  receiver:");
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 270, 24));

        jLabel8.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        jLabel8.setText("E-Mail of receiver:");
        kGradientPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 253, 24));

        jLabel9.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        jLabel9.setText("Purpose of your transfer :");
        kGradientPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, 24));

        jLabel10.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        jLabel10.setText("Amount of money:");
        kGradientPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 253, 24));

        labelfrom.setFont(new java.awt.Font("Avenir Next", 0, 36)); // NOI18N
        labelfrom.setText("BusTravelio ");
        kGradientPanel1.add(labelfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 590, 240, 60));
        kGradientPanel1.add(usernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 200, 30));
        kGradientPanel1.add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 200, 30));
        kGradientPanel1.add(purposeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 200, 30));

        amountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTextFieldActionPerformed(evt);
            }
        });
        kGradientPanel1.add(amountTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 200, 30));

        sendButton.setBackground(new java.awt.Color(0, 0, 0));
        sendButton.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        sendButton.setForeground(new java.awt.Color(255, 255, 255));
        sendButton.setText("Send");
        sendButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });
        kGradientPanel1.add(sendButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 140, 40));

        jPanel1.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountTextFieldActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        DBHandler mydbhandler= new DBHandler();
        boolean sendNow= true;
        String username = usernameTextField.getText();
        String email = emailTextField.getText();
        String amount = amountTextField.getText();
        double amount1 = Double.parseDouble(amount);
        String purpose = purposeTextField.getText();
        
        ResultSet CheckUser= mydbhandler.SelectData2colmn("paymentUsers", "usernamep", "emailp", username, email);
        if (mydbhandler.checkstatmentExsist(CheckUser))
        {
            System.out.println("username====>" + username +"\nemail ====>"+email);
           JOptionPane.showMessageDialog(null, "Username or email is wrong","ERROR", JOptionPane.ERROR_MESSAGE);
           sendNow=false;
        }
        //get information to insert them in DB newUser
        if( sendNow)
        {
            double amountd = Double.parseDouble(amount);
            String currentamount = null;
            String lastprice = null;
            String currentamountreceiver = null;
            String lastpriceReceiver = null;
            try {
                // getting the current mony in account
                currentamount = mydbhandler.SelectPriceFromUsers("currentp", "usernamep", sender);
            } catch (SQLException ex) {
                Logger.getLogger(GiveCouponUser.class.getName()).log(Level.SEVERE, null, ex);
            }
            double currentAmount2 = Double.parseDouble(currentamount);
            currentAmount2 -= amountd;
            if (currentAmount2 < 0){
                JOptionPane.showMessageDialog(null,"not available you will be in minus");
            }
            else{
            lastprice = Double.toString(currentAmount2);
            System.out.println(sender + lastprice);
            // Setting the current mony in the account
            mydbhandler.UpdatePayment2("currentp", lastprice, sender);
            DateAndTime dANDt = new DateAndTime();
            String date = dANDt.getDate();
            String time = dANDt.getTime();
            String sentTo = "----";
            String received = "----";
            double price = currentAmount2;
            // Setting the user story in his/her own ccount (table)
            mydbhandler.insertUserstoryP(sender, "sent", username, received,amount1 , date, time);
            // Setting the user story in receiver account
            mydbhandler.insertUserstoryP(username, "received", sentTo, sender,amount1 , date, time);
            try {
                currentamountreceiver = mydbhandler.SelectPriceFromUsers("currentp", "usernamep", username);
            } catch (SQLException ex) {
                Logger.getLogger(SendLuxcoin.class.getName()).log(Level.SEVERE, null, ex);
            }
            double currentAmount2Receiver = Double.parseDouble(currentamountreceiver);
            currentAmount2Receiver += amountd;
            lastpriceReceiver = Double.toString(currentAmount2Receiver);
            System.out.println(username + lastpriceReceiver);
            // Setting the current mony in the account
            mydbhandler.UpdatePayment2("currentp", lastpriceReceiver, username);
            JOptionPane.showMessageDialog(null,"please login with your payment to see the current status");
            dispose();
            }
        }
    }//GEN-LAST:event_sendButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LuxcoinLabel1;
    public javax.swing.JTextField amountTextField;
    public javax.swing.JTextField emailTextField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel labelfrom;
    public javax.swing.JTextField purposeTextField;
    private javax.swing.JButton sendButton;
    public javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
