/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.frauas.Bustravelio.frontend;

import static de.frauas.Bustravelio.frontend.CreateAccountPayment.jDateChooser1;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author haith
 */
public class StartWindowAfterLogin extends javax.swing.JFrame { 
    /**
     * Creates new form StartWindowAfterLogin
     */
    String username;
    public StartWindowAfterLogin(String username) {
        initComponents();
        this.username=username;
        System.out.println("Startwidow username is ->>>"+username);
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd"); 
        Date date = new Date();
        choosenDeparture.setDate(date);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelfrom1 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        quitButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        textFieldFrom = new javax.swing.JComboBox<>();
        swapButton = new javax.swing.JButton();
        textFieldTo = new javax.swing.JComboBox<>();
        choosenDeparture = new com.toedter.calendar.JDateChooser();
        chooseSeat = new com.toedter.components.JSpinField();
        comboBoxSelectClass = new javax.swing.JComboBox<>();
        labelfrom = new javax.swing.JLabel();
        labelTo = new javax.swing.JLabel();
        labelDeparture = new javax.swing.JLabel();
        labelSelectClass = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        paymentLoginButton = new javax.swing.JButton();
        validateButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        paymentNewRefisterButton2 = new javax.swing.JButton();
        LuxcoinLabel2 = new javax.swing.JLabel();
        LuxcoinLabel1 = new javax.swing.JLabel();
        LuxcoinLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        LuxcoinLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome in BusTravelio");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelfrom1.setFont(new java.awt.Font("Avenir Next", 0, 48)); // NOI18N
        labelfrom1.setForeground(new java.awt.Color(255, 255, 255));
        labelfrom1.setText("BusTravelio");
        labelfrom1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        getContentPane().add(labelfrom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 70));

        jLabel34.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLabel34.setText("Payment now one step easier");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 850, 180, -1));

        kGradientPanel1.setkEndColor(new java.awt.Color(254, 245, 245));
        kGradientPanel1.setkGradientFocus(0);
        kGradientPanel1.setkStartColor(new java.awt.Color(47, 62, 96));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        quitButton.setBackground(new java.awt.Color(0, 0, 0));
        quitButton.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        quitButton.setForeground(new java.awt.Color(255, 255, 255));
        quitButton.setText("Sign Out");
        quitButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });
        kGradientPanel1.add(quitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 20, 140, 40));

        jPanel1.setBackground(new java.awt.Color(254, 245, 245));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textFieldFrom.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        textFieldFrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Frankfurt am Main", "Berlin", "Köln", "Hannover", "Hamburg", "München", "Leipzig", "Stuttgart" }));
        textFieldFrom.setToolTipText("");
        textFieldFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldFromActionPerformed(evt);
            }
        });
        jPanel1.add(textFieldFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 160, 40));

        swapButton.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        swapButton.setText("Swap");
        swapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swapButtonActionPerformed(evt);
            }
        });
        jPanel1.add(swapButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 80, 40));

        textFieldTo.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        textFieldTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Berlin", "Frankfurt am Main", "Köln", "Hannover", "Hamburg", "München", "Leipzig", "Stuttgart" }));
        textFieldTo.setDoubleBuffered(true);
        textFieldTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldToActionPerformed(evt);
            }
        });
        jPanel1.add(textFieldTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 150, 40));
        jPanel1.add(choosenDeparture, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 120, 40));

        chooseSeat.setMaximum(80);
        chooseSeat.setMinimum(1);
        chooseSeat.setValue(1);
        jPanel1.add(chooseSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 60, 40));

        comboBoxSelectClass.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        comboBoxSelectClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Economy class", "First class( +40 € )" }));
        comboBoxSelectClass.setToolTipText("");
        comboBoxSelectClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxSelectClassActionPerformed(evt);
            }
        });
        jPanel1.add(comboBoxSelectClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 150, 40));

        labelfrom.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        labelfrom.setText("From");
        jPanel1.add(labelfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 34, -1));

        labelTo.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        labelTo.setText("To");
        jPanel1.add(labelTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 34, -1));

        labelDeparture.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        labelDeparture.setText("Departure");
        jPanel1.add(labelDeparture, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        labelSelectClass.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        labelSelectClass.setText("Select class");
        jPanel1.add(labelSelectClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 150, 20));

        kGradientPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 860, 110));

        jLabel19.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel19.setText(" Tickets on your phone");
        jLabel19.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(254, 245, 245)));
        kGradientPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 530, -1, 30));

        paymentLoginButton.setBackground(new java.awt.Color(0, 0, 0));
        paymentLoginButton.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        paymentLoginButton.setForeground(new java.awt.Color(255, 255, 255));
        paymentLoginButton.setText("Sign In");
        paymentLoginButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        paymentLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentLoginButtonActionPerformed(evt);
            }
        });
        kGradientPanel1.add(paymentLoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 140, 40));

        validateButton.setBackground(new java.awt.Color(0, 0, 0));
        validateButton.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        validateButton.setForeground(new java.awt.Color(255, 255, 255));
        validateButton.setText("Search");
        validateButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        validateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateButtonActionPerformed(evt);
            }
        });
        kGradientPanel1.add(validateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 170, 140, 40));

        resetButton.setBackground(new java.awt.Color(0, 0, 0));
        resetButton.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        resetButton.setForeground(new java.awt.Color(255, 255, 255));
        resetButton.setText("Reset");
        resetButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        kGradientPanel1.add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 170, 140, 40));

        paymentNewRefisterButton2.setBackground(new java.awt.Color(0, 0, 0));
        paymentNewRefisterButton2.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        paymentNewRefisterButton2.setForeground(new java.awt.Color(255, 255, 255));
        paymentNewRefisterButton2.setText("Sign Up");
        paymentNewRefisterButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        paymentNewRefisterButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentNewRefisterButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(paymentNewRefisterButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 140, 40));

        LuxcoinLabel2.setFont(new java.awt.Font("Ayuthaya", 1, 14)); // NOI18N
        LuxcoinLabel2.setForeground(new java.awt.Color(255, 255, 255));
        LuxcoinLabel2.setText("TravelioCoin Partner");
        kGradientPanel1.add(LuxcoinLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 270, -1));

        LuxcoinLabel1.setFont(new java.awt.Font("Avenir Next", 1, 18)); // NOI18N
        LuxcoinLabel1.setForeground(new java.awt.Color(255, 255, 255));
        LuxcoinLabel1.setText("TravelioCoin Sign In/Up");
        kGradientPanel1.add(LuxcoinLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 220, 40));

        LuxcoinLabel4.setFont(new java.awt.Font("Ayuthaya", 1, 36)); // NOI18N
        LuxcoinLabel4.setText("TravelioCoin");
        kGradientPanel1.add(LuxcoinLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 790, 270, 54));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel6.setText("Support on vour journey ");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(254, 245, 245)));
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 530, -1, 30));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel7.setText("COVID-19 travel Info ");
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(254, 245, 245)));
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 580, -1, 30));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setText("Download the free Bustravelio app for expertise you can count on, ");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 420, -1, 30));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel5.setText("and travel with confidence");
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 450, -1, 30));

        jLabel33.setFont(new java.awt.Font("Avenir Next", 0, 36)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(254, 245, 245));
        jLabel33.setText("The Go-To app for travelers");
        kGradientPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 330, 490, 40));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel9.setText("Updates and reminders");
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(254, 245, 245)));
        kGradientPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 580, -1, 30));

        jLabel17.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(254, 245, 245)));
        kGradientPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 10, 420));

        jLabel1.setFont(new java.awt.Font("Avenir Next", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 245, 245));
        jLabel1.setText("Lets find your next destination...");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 550, -1));

        jLabel26.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(254, 245, 245)));
        kGradientPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 190, 40));

        jLabel13.setFont(new java.awt.Font("Avenir", 0, 24)); // NOI18N
        jLabel13.setText("Paris");
        kGradientPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, -1, 30));

        jLabel14.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        jLabel14.setText("from 90€");
        kGradientPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, -1, -1));

        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(254, 245, 245)));
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 200, 40));

        jLabel12.setFont(new java.awt.Font("Avenir", 0, 24)); // NOI18N
        jLabel12.setText("Amsterdam");
        kGradientPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, -1, 30));

        jLabel15.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        jLabel15.setText("from 80€");
        kGradientPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, -1, -1));

        jLabel11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(254, 245, 245)));
        kGradientPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 190, 40));

        jLabel22.setFont(new java.awt.Font("Avenir", 0, 24)); // NOI18N
        jLabel22.setText("Frankfurt");
        kGradientPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, -1, -1));

        jLabel23.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        jLabel23.setText("from 15€");
        kGradientPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, -1, -1));

        jLabel21.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(254, 245, 245)));
        kGradientPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, 200, 40));

        jLabel24.setFont(new java.awt.Font("Avenir", 0, 24)); // NOI18N
        jLabel24.setText("Hamburg");
        kGradientPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, -1, -1));

        jLabel25.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        jLabel25.setText("from 50€");
        kGradientPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 560, -1, -1));

        jLabel16.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(254, 245, 245)));
        kGradientPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 580, 190, 30));

        jLabel27.setFont(new java.awt.Font("Avenir", 0, 24)); // NOI18N
        jLabel27.setText("Köln");
        kGradientPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 610, -1, -1));

        jLabel28.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        jLabel28.setText("from 30€");
        kGradientPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 640, -1, -1));

        jLabel29.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(254, 245, 245)));
        kGradientPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 580, 200, 30));

        jLabel30.setFont(new java.awt.Font("Avenir", 0, 24)); // NOI18N
        jLabel30.setText("Düsseldorf");
        kGradientPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 610, -1, -1));

        jLabel31.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        jLabel31.setText("from 45€");
        kGradientPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 640, -1, -1));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 900));

        jLabel18.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel18.setText(" Tickets on your phone");
        jLabel18.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(254, 245, 245)));
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 500, -1, 30));

        LuxcoinLabel3.setFont(new java.awt.Font("Ayuthaya", 1, 36)); // NOI18N
        LuxcoinLabel3.setText("TravelioCoin");
        getContentPane().add(LuxcoinLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 790, 270, 54));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void swapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_swapButtonActionPerformed
        String swapping = textFieldFrom.getSelectedItem().toString();
        textFieldFrom.setSelectedItem(textFieldTo.getSelectedItem().toString());//setText(textFieldTo.getText());
        textFieldTo.setSelectedItem(swapping);
    }//GEN-LAST:event_swapButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // Noch sicher stellen 
       
        
// Reset choosen Set 
        chooseSeat.setMaximum(80);
        chooseSeat.setMinimum(1);
        chooseSeat.setValue(1);
        
// Reset choosen Departure
        choosenDeparture.setDate(null);
    
//reset Choosen class
        comboBoxSelectClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Economec", "First class" }));
        
// Reset Textfield From and To
        textFieldFrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Frankfurt am Main", "Berlin", "München", "Stuttgart" }));
        textFieldFrom.setToolTipText("");
        textFieldFrom.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldFromActionPerformed(evt);
            }
        });
        textFieldTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Frankfurt am Main", "Berlin", "München", "Stuttgart" }));
        textFieldTo.setSelectedIndex(1);
        textFieldTo.setDoubleBuffered(true);
        textFieldTo.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldToActionPerformed(evt);
            }
        });
        
    }//GEN-LAST:event_resetButtonActionPerformed

    private void validateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateButtonActionPerformed

        
       String From=(String) textFieldFrom.getSelectedItem();
      String To=(String) textFieldTo.getSelectedItem();
      Date datum= choosenDeparture.getDate();
      System.out.println("datum---->"+datum);
      int year=datum.getYear()+1900;
      int day=datum.getDate();
      int month=datum.getMonth()+1;

      String date=year+"-"+month+"-"+day;
        System.out.println("datum---->"+date);
        int seat=chooseSeat.getValue();
         String classart=(String) comboBoxSelectClass.getSelectedItem();
                System.out.println("class --> "+classart);
        new result(username,From,To,date,seat,classart).setVisible(true);
         

    }//GEN-LAST:event_validateButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitButtonActionPerformed

    private void comboBoxSelectClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxSelectClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxSelectClassActionPerformed

    private void textFieldFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldFromActionPerformed

    private void textFieldToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldToActionPerformed
        
    }//GEN-LAST:event_textFieldToActionPerformed

    private void paymentLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentLoginButtonActionPerformed
        new PaymentLogin().setVisible(true);
    }//GEN-LAST:event_paymentLoginButtonActionPerformed

    private void paymentNewRefisterButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentNewRefisterButton2ActionPerformed
        new CreateAccountPayment().setVisible(true);
    }//GEN-LAST:event_paymentNewRefisterButton2ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LuxcoinLabel1;
    private javax.swing.JLabel LuxcoinLabel2;
    private javax.swing.JLabel LuxcoinLabel3;
    private javax.swing.JLabel LuxcoinLabel4;
    private com.toedter.components.JSpinField chooseSeat;
    private com.toedter.calendar.JDateChooser choosenDeparture;
    private javax.swing.JComboBox<String> comboBoxSelectClass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel labelDeparture;
    private javax.swing.JLabel labelSelectClass;
    private javax.swing.JLabel labelTo;
    private javax.swing.JLabel labelfrom;
    private javax.swing.JLabel labelfrom1;
    private javax.swing.JButton paymentLoginButton;
    private javax.swing.JButton paymentNewRefisterButton2;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton swapButton;
    private javax.swing.JComboBox<String> textFieldFrom;
    private javax.swing.JComboBox<String> textFieldTo;
    private javax.swing.JButton validateButton;
    // End of variables declaration//GEN-END:variables

      private javax.swing.JButton admin;
}
