/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.frauas.Bustravelio.frontend;

import de.frauas.Bustravelio.backend.DBHandler;
import static de.frauas.Bustravelio.backend.DBHandler.connect;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mohamad Fakher
 */
public  class Travelsmanagement extends javax.swing.JFrame {
    String sql;
    DefaultTableModel model;
    String From;
    String To;
    /**
     * Creates new form result
     */
    public Travelsmanagement() {
        this.From=From;
        this.To=To;
        initComponents();
        showTravels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelfrom = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Your Travels");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelfrom.setFont(new java.awt.Font("Avenir Next", 0, 48)); // NOI18N
        labelfrom.setForeground(new java.awt.Color(255, 255, 255));
        labelfrom.setText("BusTravelio");
        getContentPane().add(labelfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 50));

        kGradientPanel1.setkEndColor(new java.awt.Color(254, 245, 245));
        kGradientPanel1.setkGradientFocus(0);
        kGradientPanel1.setkStartColor(new java.awt.Color(47, 62, 96));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Avenir Next", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Your Travels ");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 270, 40));

        jTable1.setBackground(new java.awt.Color(254, 245, 245));
        jTable1.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "From", "To", "Departure Date", "Departure Time", "Arrival ", "Price", "Seat"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getAccessibleContext().setAccessibleDescription("");

        kGradientPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 1310, 240));

        jLabel2.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        jLabel2.setText("From");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 110, 30));

        jLabel3.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        jLabel3.setText("To");
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));
        kGradientPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 110, 30));

        jLabel4.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        jLabel4.setText("Depature Date");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 130, -1));
        kGradientPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 160, 30));

        jLabel5.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        jLabel5.setText("Depature Time");
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 130, -1));
        kGradientPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 170, 30));

        jLabel6.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        jLabel6.setText("Arrive Time");
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 100, 20));
        kGradientPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 130, 30));

        jLabel8.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        jLabel8.setText("Seat");
        kGradientPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 110, 100, 20));
        kGradientPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 140, 110, 30));

        jLabel7.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        jLabel7.setText("Price");
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 110, 100, -1));
        kGradientPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 140, 110, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 140, 90, 30));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update");
        jButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 30, 140, 30));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Delete");
        jButton3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 140, 80, 30));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Back");
        jButton4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButton(evt);
            }
        });
        kGradientPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 30, 140, 30));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model =(DefaultTableModel)jTable1.getModel();
        int  selectedRowIndex = jTable1.getSelectedRow();
        jTextField1.setText((String) model.getValueAt(selectedRowIndex,1).toString());
        jTextField2.setText((String) model.getValueAt(selectedRowIndex,2).toString());
        jTextField3.setText((String) model.getValueAt(selectedRowIndex,3).toString());
        jTextField4.setText((String) model.getValueAt(selectedRowIndex,4).toString());
        jTextField5.setText((String) model.getValueAt(selectedRowIndex,5).toString());
        jTextField6.setText((String) model.getValueAt(selectedRowIndex,6).toString());
        jTextField7.setText((String) model.getValueAt(selectedRowIndex,7).toString());

    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      
      try (Connection myConn= connect();) {
              String insertsql= "INSERT INTO travels (`fromcity`,`tocity`,`Datum`,`departureTime`,`arriveTime`,`price`,`place`) "
                 + "VALUES('"+jTextField1.getText()+"',"+"'"+jTextField2.getText()+"','"+jTextField3.getText()+"',"
                 + ""+"'"+jTextField4.getText()+"',"+"'"+jTextField5.getText()+"','"+jTextField6.getText()+"',"
                 + "'"+jTextField7.getText()+"');"; 
    		        
            System.out.println("Erfolgreich mit Datenbank verbunden."); 			        	
            Statement stmt = myConn.createStatement();
            stmt.execute(insertsql);
            stmt.close();
            }
            catch(SQLException ex) {		          	
                    System.err.println(ex.getMessage());
            }	
	        // get selected row index
        Vector ntravel= new Vector();
     
        ntravel.add("");
        ntravel.add(jTextField1.getText());
        ntravel.add(jTextField2.getText());
        ntravel.add(jTextField3.getText());
        ntravel.add(jTextField4.getText());
        ntravel.add(jTextField5.getText());
        ntravel.add(jTextField6.getText());
        ntravel.add(jTextField7.getText());
        
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.addRow(ntravel);
          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
	        // get selected row index
        int selectedRowIndex = jTable1.getSelectedRow();
        if(selectedRowIndex>=0){
        model.setValueAt(jTextField1.getText(),selectedRowIndex,1);
        model.setValueAt(jTextField2.getText(),selectedRowIndex,2);
        model.setValueAt(jTextField3.getText(),selectedRowIndex,3);
        model.setValueAt(jTextField4.getText(),selectedRowIndex,4);
        model.setValueAt(jTextField5.getText(),selectedRowIndex,5);
        model.setValueAt(jTextField6.getText(),selectedRowIndex,6);
        model.setValueAt(jTextField7.getText(),selectedRowIndex,7);
        }
        else{
            System.out.println("Error");
        }
        String id = model.getValueAt(selectedRowIndex, 0).toString();
        try (Connection myConn= connect();) {
            String query=" UPDATE travels SET fromcity='"+jTextField1.getText()+"'"
                    + ",tocity='"+jTextField2.getText()+"'"
                    + ",Datum='"+jTextField3.getText()+"'"
                    + ",departureTime='"+jTextField4.getText()+"'"
                    + ",arriveTime='"+jTextField5.getText()+"'"
                    + ",price='"+jTextField6.getText()+"'"
                    + ",place='"+jTextField7.getText()+"' where id ='"+id+"'";
				        
            System.out.println("Erfolgreichhhhhhh"); 			        	
            Statement stmt = myConn.createStatement();
            stmt.execute(query);
            stmt.close();
            }
            catch(SQLException ex) {		          	
                    System.err.println(ex.getMessage());
            }	
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        DefaultTableModel model =(DefaultTableModel)jTable1.getModel();
        int  selectedRowIndex = jTable1.getSelectedRow();
        
         String id = model.getValueAt(selectedRowIndex, 0).toString();
        
          jTable1.removeRowSelectionInterval(selectedRowIndex, 0);
          
          if(jTable1.getSelectedRowCount()==0) {
	        	model.removeRow(selectedRowIndex);
	        	
	        	 try (Connection myConn= connect();) {
				        String query="  delete from travels where id ='"+id+"'";

				        
			        	System.out.println("Erfolgreich mit Datenbank verbunden."); 	
			        	
			            Statement stmt = myConn.createStatement();
			         	stmt.execute(query);
			         	stmt.close();
			       	    }catch(SQLException ex) {
			          	
			          	System.err.println(ex.getMessage());
			             }	
	        }
	        else {
                JOptionPane.showMessageDialog(null,"Pleas selecte single row");

	        }	
    }//GEN-LAST:event_jButton3ActionPerformed

    private void BackButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButton
        // TODO add your handling code here:
      dispose();
        
    }//GEN-LAST:event_BackButton
        DBHandler tt = new DBHandler();
        public void showTravels(){
         ArrayList<Travels> list = tt.travellist();
          model = (DefaultTableModel)jTable1.getModel();
         Object [] row = new Object[8];
            for(int i =0; i<list.size();i++){
                row[0]=list.get(i).getId();
                row[1]=list.get(i).getfromcity();
                row[2]=list.get(i).gettocity();
                row[3]=list.get(i).getdatum();
                row[4]=list.get(i).getdepartureTime();
                row[5]=list.get(i).getarriveTime();
                row[6]=list.get(i).getprice();
                row[7]=list.get(i).getseat();

                model.addRow(row);
            }
        }
        
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel labelfrom;
    // End of variables declaration//GEN-END:variables
}
