/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.frauas.Bustravelio.frontend;

import de.frauas.Bustravelio.backend.DBHandler;
import de.frauas.Bustravelio.backend.Encryption;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.validator.routines.EmailValidator;

/**
 *
 * @author User
 */
public class UsermanagementPayment extends javax.swing.JFrame {
    
    String username;
    /**
     * Creates new form Usermanagement
     */
    public UsermanagementPayment() {
        initComponents();
    }
userPayment user;

    /**
     * Constructor of UserManagement JFrame
     *
     * @param username
     */
    public UsermanagementPayment(String username) {
        initComponents();
        this.username = username;
    }

    /**
     * Opens EventAddJframe
     *
     * @see backButton
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userName_jTextField = new javax.swing.JTextField();
        email_address_jTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Search_user_jTextField = new javax.swing.JTextField();
        Search_User_jButton = new javax.swing.JButton();
        jTextField1Password = new javax.swing.JTextField();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        labelfrom = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LuxcoinLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        search_user_jLabel1 = new javax.swing.JLabel();
        User_name_jLabel1 = new javax.swing.JLabel();
        email_address_jLabel1 = new javax.swing.JLabel();
        password_jLabel1 = new javax.swing.JLabel();
        isAdmin_jCheckBox = new javax.swing.JCheckBox();
        DeleteUserjButton1 = new javax.swing.JButton();
        editAndSaveButton1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        show_all_user_jButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("USER MANAGEMENT");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(userName_jTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 300, 30));
        getContentPane().add(email_address_jTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 300, 30));

        jTable1.setBackground(new java.awt.Color(254, 245, 245));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Email Address", "Password ", "IsAdmin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 950, 480));
        getContentPane().add(Search_user_jTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 157, -1));

        Search_User_jButton.setText("Search");
        Search_User_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_User_jButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Search_User_jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));
        getContentPane().add(jTextField1Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 300, 30));

        kGradientPanel1.setkEndColor(new java.awt.Color(254, 245, 245));
        kGradientPanel1.setkGradientFocus(0);
        kGradientPanel1.setkStartColor(new java.awt.Color(47, 62, 96));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelfrom.setFont(new java.awt.Font("Avenir Next", 0, 48)); // NOI18N
        labelfrom.setForeground(new java.awt.Color(255, 255, 255));
        labelfrom.setText("BusTravelio");
        kGradientPanel1.add(labelfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 60));

        jLabel1.setFont(new java.awt.Font("Avenir Next", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User Management ");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 330, 70));

        LuxcoinLabel1.setFont(new java.awt.Font("Ayuthaya", 1, 36)); // NOI18N
        LuxcoinLabel1.setText("TravelioCoin");
        kGradientPanel1.add(LuxcoinLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 800, 270, 54));

        jLabel4.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N
        jLabel4.setText("Payment now one step easier");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 860, 390, -1));

        search_user_jLabel1.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        search_user_jLabel1.setText("Search User :");
        kGradientPanel1.add(search_user_jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        User_name_jLabel1.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        User_name_jLabel1.setText("Username :");
        kGradientPanel1.add(User_name_jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 101, -1));

        email_address_jLabel1.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        email_address_jLabel1.setText("Email Addresse : ");
        kGradientPanel1.add(email_address_jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        password_jLabel1.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        password_jLabel1.setText("Password :");
        kGradientPanel1.add(password_jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 110, -1));

        isAdmin_jCheckBox.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        isAdmin_jCheckBox.setText("isAdmin");
        kGradientPanel1.add(isAdmin_jCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, -1, -1));

        DeleteUserjButton1.setBackground(new java.awt.Color(0, 0, 0));
        DeleteUserjButton1.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        DeleteUserjButton1.setForeground(new java.awt.Color(255, 255, 255));
        DeleteUserjButton1.setText("Delete User");
        DeleteUserjButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        DeleteUserjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteUserjButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(DeleteUserjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 630, 140, 40));

        editAndSaveButton1.setBackground(new java.awt.Color(0, 0, 0));
        editAndSaveButton1.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        editAndSaveButton1.setForeground(new java.awt.Color(255, 255, 255));
        editAndSaveButton1.setText("Save");
        editAndSaveButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        editAndSaveButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAndSaveButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(editAndSaveButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 630, 140, 40));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 30, 140, 40));

        show_all_user_jButton.setBackground(new java.awt.Color(0, 0, 0));
        show_all_user_jButton.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        show_all_user_jButton.setForeground(new java.awt.Color(255, 255, 255));
        show_all_user_jButton.setText("Show all users");
        show_all_user_jButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        show_all_user_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_all_user_jButtonActionPerformed(evt);
            }
        });
        kGradientPanel1.add(show_all_user_jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 670, 140, 40));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void show_all_user_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_all_user_jButtonActionPerformed
        // TODO add your handling code here:  private void jButtonAcessToUsersActionPerformed(java.awt.event.ActionEvent evt) {                                                    

        ArrayList<userPayment> userList = new ArrayList<>();
        DBHandler mydbhandler = new DBHandler();
        //Connection myConn = mydbhandler.connect();
        ResultSet rs = mydbhandler.GetAllUserp(/*myConn*/"paymentUsers");
        userPayment user;
        
            try {
                while (rs.next()) {
                    user = new userPayment(rs.getString("usernamep"), rs.getString("emailp"), rs.getString("passwordp"), rs.getBoolean("isAdminp"));
                    userList.add(user);
                }
            } catch (SQLException ex) {
                Logger.getLogger(UsermanagementPayment.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setNumRows(0);
        Object[] row = new Object[4];
        for (int i = 0; i < userList.size(); i++) {
            row[0] = userList.get(i).usernamep;
            row[1] = userList.get(i).emailp;
            row[2] = userList.get(i).passwordp;
            row[3] = userList.get(i).isAdminp;

            model.addRow(row);
        }
        /*try {
            myConn.close();
        } catch (SQLException ex) {
            Logger.getLogger(Usermanagement.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_show_all_user_jButtonActionPerformed

    
  
    private void Search_User_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_User_jButtonActionPerformed
        // TODO add your handling code here:
        
        String userTObeEdit = Search_user_jTextField.getText();
        DBHandler mydbhandler= new DBHandler();
        //Connection myConn = mydbhandler.connect();
        ResultSet rsForUser= mydbhandler.Selectdata(/*myConn,*/"paymentUsers", "usernamep", Search_user_jTextField.getText());
        
        if(!mydbhandler.checkstatmentExsist(rsForUser))
        {
            JOptionPane.showMessageDialog(null, "username does not exist", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else {
            userPayment user = mydbhandler.GetUserPayment(userTObeEdit);
            //user= mydbhandler.GetUserPayment(/*myConn,*/userTObeEdit);
            userName_jTextField.setText(user.usernamep);
            email_address_jTextField.setText(user.emailp);
            jTextField1Password.setText(user.passwordp);
            
            if(user.isAdminp)
            {
               isAdmin_jCheckBox.setSelected(true);
            }
            else{
                isAdmin_jCheckBox.setSelected(false);
            }
            
        }/*
        try {
            myConn.close();
        } catch (SQLException ex) {
            Logger.getLogger(Usermanagement.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_Search_User_jButtonActionPerformed

    private void editAndSaveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAndSaveButton1ActionPerformed
        // TODO add your handling code here:
        String emailGiven=email_address_jTextField.getText();
        String usernameGiven=Search_user_jTextField.getText();
        DBHandler mydbhandler = new DBHandler();
        //Connection myConn = mydbhandler.connect();
        
         userPayment toBeEditedUser = mydbhandler.GetUserPayment(/*myConn,*/"PaymentUsers");
        String hash;
        
//        System.out.println(toBeEditedUser.passwordp.toString() );
        
        System.out.println( jTextField1Password.getText());

        if (!jTextField1Password.getText().matches(toBeEditedUser.passwordp)) {

            Encryption enc = new Encryption(jTextField1Password.getText());

            hash = enc.HaschCode();
        } 
        else {
            hash = toBeEditedUser.passwordp;
        }
        mydbhandler.EditUserPayment(/*myConn,*/"paymentUsers", "usernamep", userName_jTextField.getText(), "usernamep", Search_user_jTextField.getText());
        mydbhandler.EditUserPayment(/*myConn,*/"paymentUsers", "passwordp",hash,"usernamep" ,Search_user_jTextField.getText());


        

        boolean Validate = EmailValidator.getInstance().isValid(email_address_jTextField.getText());

        if (Validate == false) {
            JOptionPane.showMessageDialog(null, "Please enter a valid E-Mail address!", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            mydbhandler.EditUserPayment(/*myConn,*/"paymentUsers", "emailp",email_address_jTextField.getText(),"usernamep" ,Search_user_jTextField.getText());


        }

        if (isAdmin_jCheckBox.isSelected()) {
            mydbhandler.EditUserPayment(/*myConn,*/"paymentUsers", "isAdminp", "yes", "usernamep", Search_user_jTextField.getText());
        } else {
            mydbhandler.EditUserPayment(/*myConn,*/"paymentUsers", "isAdminp", "no", "usernamep", Search_user_jTextField.getText());

        }

        JOptionPane.showMessageDialog(null, "User edited !", "Info", JOptionPane.INFORMATION_MESSAGE);
        /*try {
            myConn.close();
            // mydbhandler.close(myConn);
        } catch (SQLException ex) {
            Logger.getLogger(Usermanagement.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_editAndSaveButton1ActionPerformed

    private void DeleteUserjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteUserjButton1ActionPerformed
        // TODO add your handling code here:
        String user= Search_user_jTextField.getText();
        DBHandler mydbhandler= new DBHandler();
        //Connection myConn = mydbhandler.connect();
        int updated= mydbhandler.DeleteUser(/*myConn,*/"paymentUsers", "usernamep", user);
        if(updated==1 )
        {
            JOptionPane.showMessageDialog(null, "User deleted !", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
       /* try {
            myConn.close();
        } catch (SQLException ex) {
            Logger.getLogger(UsermanagementPayment.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_DeleteUserjButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
   //   System.exit(0);
    dispose();
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        /*
         DefaultTableModel model =(DefaultTableModel)jTable1.getModel();
        int  selectedRowIndex = jTable1.getSelectedRow();
        userName_jTextField.setText((String) model.getValueAt(selectedRowIndex,0).toString());
        email_address_jTextField.setText((String) model.getValueAt(selectedRowIndex,1).toString());
        jTextField1Password.setText((String) model.getValueAt(selectedRowIndex,2).toString());
        String isadmin= ((String) model.getValueAt(selectedRowIndex,3).toString());
        
        if(isadmin=="true")
            {
               isAdmin_jCheckBox.setSelected(true);
            }
            else{
                isAdmin_jCheckBox.setSelected(false);
            }    
        */
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteUserjButton1;
    private javax.swing.JLabel LuxcoinLabel1;
    private javax.swing.JButton Search_User_jButton;
    private javax.swing.JTextField Search_user_jTextField;
    private javax.swing.JLabel User_name_jLabel1;
    private javax.swing.JButton editAndSaveButton1;
    private javax.swing.JLabel email_address_jLabel1;
    private javax.swing.JTextField email_address_jTextField;
    private javax.swing.JCheckBox isAdmin_jCheckBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1Password;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel labelfrom;
    private javax.swing.JLabel password_jLabel1;
    private javax.swing.JLabel search_user_jLabel1;
    private javax.swing.JButton show_all_user_jButton;
    private javax.swing.JTextField userName_jTextField;
    // End of variables declaration//GEN-END:variables
}
